[workspace]
members = [
    "rust_src/mac_types",
    "rust_src/kernel",
    "rust_src/os",
]
resolver = "2"

[profile.release]
lto = true
opt-level = "s"
panic = "abort"

[profile.dev]
panic = "abort"
